/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as ParkingSummaryRouteImport } from './routes/parking-summary'
import { Route as ParkingPlanRouteImport } from './routes/parking-plan'
import { Route as LotsMobileRouteImport } from './routes/lots-mobile'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingSummaryRoute = ParkingSummaryRouteImport.update({
  id: '/parking-summary',
  path: '/parking-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingPlanRoute = ParkingPlanRouteImport.update({
  id: '/parking-plan',
  path: '/parking-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsMobileRoute = LotsMobileRouteImport.update({
  id: '/lots-mobile',
  path: '/lots-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consulting': typeof ConsultingRoute
  '/lots-mobile': typeof LotsMobileRoute
  '/parking-plan': typeof ParkingPlanRoute
  '/parking-summary': typeof ParkingSummaryRoute
  '/presentation': typeof PresentationRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consulting': typeof ConsultingRoute
  '/lots-mobile': typeof LotsMobileRoute
  '/parking-plan': typeof ParkingPlanRoute
  '/parking-summary': typeof ParkingSummaryRoute
  '/presentation': typeof PresentationRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consulting': typeof ConsultingRoute
  '/lots-mobile': typeof LotsMobileRoute
  '/parking-plan': typeof ParkingPlanRoute
  '/parking-summary': typeof ParkingSummaryRoute
  '/presentation': typeof PresentationRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/consulting'
    | '/lots-mobile'
    | '/parking-plan'
    | '/parking-summary'
    | '/presentation'
    | '/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/consulting'
    | '/lots-mobile'
    | '/parking-plan'
    | '/parking-summary'
    | '/presentation'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/consulting'
    | '/lots-mobile'
    | '/parking-plan'
    | '/parking-summary'
    | '/presentation'
    | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConsultingRoute: typeof ConsultingRoute
  LotsMobileRoute: typeof LotsMobileRoute
  ParkingPlanRoute: typeof ParkingPlanRoute
  ParkingSummaryRoute: typeof ParkingSummaryRoute
  PresentationRoute: typeof PresentationRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking-summary': {
      id: '/parking-summary'
      path: '/parking-summary'
      fullPath: '/parking-summary'
      preLoaderRoute: typeof ParkingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking-plan': {
      id: '/parking-plan'
      path: '/parking-plan'
      fullPath: '/parking-plan'
      preLoaderRoute: typeof ParkingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots-mobile': {
      id: '/lots-mobile'
      path: '/lots-mobile'
      fullPath: '/lots-mobile'
      preLoaderRoute: typeof LotsMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConsultingRoute: ConsultingRoute,
  LotsMobileRoute: LotsMobileRoute,
  ParkingPlanRoute: ParkingPlanRoute,
  ParkingSummaryRoute: ParkingSummaryRoute,
  PresentationRoute: PresentationRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
